### ISSUE TITLE
Load time: Unregistering sometimes create problem

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/micro-frontends-challenges-app#142]
This does not happen always - but happens after 3/4 register/unregister. 

**Summary:**

**Steps to Reproduce:**

1. Try to register and later unregister a challenge for several times. https://platform.topcoder.com/earn/find/challenges/bc959f3c-3f90-412a-81b4-e6ae29199ded?tab=registrants

**Actual Result:**

Sometimes there are some exceptions. 

**Expected Result:**

It should unregister always. 

**Environment Details:**

Edition :	Windows 10 Pro Version 21H1
OS build :	19043.1237
Windows Feature Experience Pack 120.2212.3530.0

***Browser and version:***

![s6](/uploads/ed33d73d3a145cb5fa92c19ff7cd1258/s6.mp4)Chrome version 94.0.4606.81 (Official Build) (64-bit)

**Screen recording or Screen snapshot:**

Failed to load resource: the server responded with a status of 500 ()
bc959f3c-3f90-412a-81b4-e6ae29199ded:1 The resource https://cdn.jsdelivr.net/npm/single-spa@5.5.5/lib/system/single-spa.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
api.topcoder.com/v5/challenges/bc959f3c-3f90-412a-81b4-e6ae29199ded?:1 Failed to load resource: the server responded with a status of 504 ()
zone.min.js:21 Unhandled Promise rejection:  ; Zone: <root> ; Task: Promise.then ; Value: Error
    at E (/challenges-app/topcoder-micro-frontends-challenges-app.js:21)
    at e.invoke (zone.min.js:13)
    at t.run (zone.min.js:13)
    at zone.min.js:21
    at e.invokeTask (zone.min.js:13)
    at t.runTask (zone.min.js:13)
    at _ (zone.min.js:13) Error
    at E (https://platform.topcoder.com/challenges-app/topcoder-micro-frontends-challenges-app.js:21:10058)
    at e.invoke (https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:13:7171)
    at t.run (https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:13:2271)
    at https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:21:2755
    at e.invokeTask (https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:13:7855)
    at t.runTask (https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:13:2934)
    at _ (https://cdn.jsdelivr.net/npm/zone.js@0.10.3/dist/zone.min.js:13:10171)
Zone.__load_patch.n.onUnhandledError @ zone.min.js:21
/community-app-assets/api/logger:1 Failed to load resource: the server responded with a status of 404 ()
api.topcoder.com/v5/resources:1 Failed to load resource: the server responded with a status of 404 ()
zone.min.js:21 Unhandled Promise rejection:  ; Zone: <root> ; Task: Promise.then ; Value: Error
    at S.unregister (/challenges-app/topcoder-micro-frontends-challenges-app.js:21) Error
    at S.unregister (https://platform.topcoder.com/challenges-app/topcoder-micro-frontends-challenges-app.js:21:17676)
Zone.__load_patch.n.onUnhandledError @ zone.min.js:21
/community-app-assets/api/logger:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by LieutenantRoger** [comment]
This appears to be a network latency issue
